#!/usr/bin/env python3
"""
Auto-generated pyvsc translation from SystemVerilog

IMPORTANT: This is a SUGGESTED translation that requires manual review.
Please verify:
1. All constraint semantics are preserved
2. Data type mappings are correct
3. Distribution weights match original intent
4. Solve order effects are equivalent

Generated by: SV-to-pyvsc Translation Assistant
"""

import vsc
from enum import IntEnum
import random
from typing import Optional

# =============================================================================
# BASE CLASS STUBS (from UVM or other libraries)
# Replace these with actual implementations or imports as needed
# =============================================================================

@vsc.randobj
class UvmSequenceItem:
  """
  Stub for uvm_sequence_item base class.
  Replace with actual implementation or import from your UVM library.
  """
  def __init__(self):
    pass  # TODO: Add base class fields if needed


@vsc.randobj
class IspYuv2rgbRandItem(UvmSequenceItem):
  """Translated from SV class: isp_yuv2rgb_rand_item"""

  def __init__(self):
    super().__init__()
    self.IsBypassMode = vsc.rand_bit_t(32)
    self.IsYuvFormat = vsc.rand_bit_t(32)
    self.IsImageWidth = vsc.rand_bit_t(32)
    self.IsImageHeight = vsc.rand_bit_t(32)
    self.IsGridMode = vsc.rand_bit_t(32)
    self.enable = vsc.rand_bit_t(32)
    self.chroma_enabled = vsc.rand_bit_t(32)
    self.dither_enable = vsc.rand_bit_t(32)
    self.clip_enable = vsc.rand_bit_t(32)
    self.width = vsc.rand_bit_t(32)
    self.height = vsc.rand_bit_t(32)
    self.IsInWidth = vsc.rand_bit_t(32)
    self.arith_width = vsc.rand_bit_t(32)
    self.stride = vsc.rand_bit_t(32)
    self.fmt = vsc.rand_bit_t(32)
    self.mode = vsc.rand_bit_t(32)
    self.range = vsc.rand_bit_t(32)
    self.signed_val = vsc.rand_int_t(32)
    self.unsigned_val = vsc.rand_bit_t(32)
    self.c00 = vsc.rand_int_t(32)
    self.c01 = vsc.rand_int_t(32)
    self.c02 = vsc.rand_int_t(32)
    self.c10 = vsc.rand_int_t(32)
    self.c11 = vsc.rand_int_t(32)
    self.c12 = vsc.rand_int_t(32)
    self.c20 = vsc.rand_int_t(32)
    self.c21 = vsc.rand_int_t(32)
    self.c22 = vsc.rand_int_t(32)
    self.y_offset = vsc.rand_int_t(32)
    self.uv_offset = vsc.rand_int_t(32)
    self.arith_y_offset = vsc.rand_int_t(32)
    self.IsRdmaDataFormatYuv = vsc.rand_bit_t(32)
    self.IsInBittageType = vsc.rand_bit_t(32)
    self.yuv_isp_image_active_width = vsc.rand_bit_t(32)
    self.yuv_isp_crop_width = vsc.rand_bit_t(32)
    self.yuv_isp_image_crop_pre_x = vsc.rand_bit_t(32)
    self.yuv_isp_scale_y = vsc.rand_int_t(32)
    self.yuv_isp_scale_shifter_y = vsc.rand_bit_t(32)
    self.yuv_isp_org_height = vsc.rand_bit_t(32)
    self.yuv_isp_image_active_height = vsc.rand_bit_t(32)
    self.yuv_format = vsc.rand_bit_t(32)
    self.yuv_packing = vsc.rand_bit_t(32)
    self.color_space = vsc.rand_bit_t(32)
    self.range_mode = vsc.rand_bit_t(32)
    self.rgb_format = vsc.rand_bit_t(32)
    self.yuv_bit_depth = vsc.rand_bit_t(32)
    self.bit_depth = vsc.rand_bit_t(32)
    self.a = vsc.rand_int_t(32)
    self.b = vsc.rand_int_t(32)
    self.c = vsc.rand_int_t(32)
    self.d = vsc.rand_int_t(32)
    self.x = vsc.rand_int_t(32)
    self.y = vsc.rand_int_t(32)
    self.z = vsc.rand_int_t(32)
    self.w = vsc.rand_int_t(32)
    self.ip_post_frame_gap = vsc.rand_bit_t(32)
    self.packet_size = vsc.rand_bit_t(32)
    self.delay_cycles = vsc.rand_bit_t(32)
    self.IsSrcCompType = vsc.rand_bit_t(32)
    self.yuv_rdmaY_img_stride_1p = vsc.rand_bit_t(32)
    self.yuv_rdmaY_sbwc_lossy_comp_mode = vsc.rand_bit_t(32)
    self.yuv_rdmaY_comp_64B_align = vsc.rand_bit_t(32)
    self.yuv_isp_out_scale_x = vsc.rand_bit_t(32)

  @vsc.constraint
  def parameter_range(self):
    self.IsBypassMode in vsc.rangelist(vsc.rng(0, 1))
    self.IsYuvFormat in vsc.rangelist(vsc.rng(0, 5))
    self.IsImageWidth in vsc.rangelist(vsc.rng(64, 16384))
    self.IsImageHeight in vsc.rangelist(vsc.rng(64, 16384))
    self.IsGridMode in vsc.rangelist(vsc.rng(0, 1))
    self.enable in vsc.rangelist(vsc.rng(0, 1))
    self.chroma_enabled in vsc.rangelist(vsc.rng(0, 1))
    self.dither_enable in vsc.rangelist(vsc.rng(0, 1))
    self.clip_enable in vsc.rangelist(vsc.rng(0, 1))
    self.width in vsc.rangelist(vsc.rng(64, 16384))
    self.height in vsc.rangelist(vsc.rng(64, 16384))
    self.IsInWidth in vsc.rangelist(vsc.rng(64, 16384))
    self.arith_width in vsc.rangelist(vsc.rng(1, 16))
    self.stride in vsc.rangelist(vsc.rng(1, 65536))
    self.fmt in vsc.rangelist(vsc.rng(0, 15))
    self.mode in vsc.rangelist(vsc.rng(0, 7))
    self.range in vsc.rangelist(vsc.rng(0, 3))
    self.signed_val in vsc.rangelist(vsc.rng(-32768, 32767))
    self.unsigned_val in vsc.rangelist(vsc.rng(0, 255))
    self.c00 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c01 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c02 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c10 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c11 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c12 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c20 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c21 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.c22 in vsc.rangelist(vsc.rng(-1024, 1024))
    self.y_offset in vsc.rangelist(vsc.rng(-1024, 1024))
    self.uv_offset in vsc.rangelist(vsc.rng(-1024, 1024))
    self.arith_y_offset in vsc.rangelist(vsc.rng(-1024, 1024))
    self.IsRdmaDataFormatYuv in vsc.rangelist(vsc.rng(4, 33))
    self.IsInBittageType in vsc.rangelist(vsc.rng(0, 3))
    self.yuv_isp_image_active_width in vsc.rangelist(vsc.rng(0, 16384))
    self.yuv_isp_crop_width in vsc.rangelist(vsc.rng(0, 16384))
    self.yuv_isp_image_crop_pre_x in vsc.rangelist(vsc.rng(0, 16384))
    self.yuv_isp_scale_y in vsc.rangelist(vsc.rng(-8192, 8191))
    self.yuv_isp_scale_shifter_y in vsc.rangelist(vsc.rng(0, 15))
    self.yuv_isp_org_height in vsc.rangelist(vsc.rng(1, 16384))
    self.yuv_isp_image_active_height in vsc.rangelist(vsc.rng(0, 16384))
    self.yuv_format in vsc.rangelist(vsc.rng(0, 2))
    self.yuv_packing in vsc.rangelist(vsc.rng(0, 2))
    self.color_space in vsc.rangelist(vsc.rng(0, 2))
    self.range_mode in vsc.rangelist(vsc.rng(0, 1))
    self.rgb_format in vsc.rangelist(vsc.rng(0, 2))
    self.yuv_bit_depth in vsc.rangelist(vsc.rng(8, 12))
    self.bit_depth in vsc.rangelist(vsc.rng(8, 12))
    self.a in vsc.rangelist(vsc.rng(-32768, 32767))
    self.b in vsc.rangelist(vsc.rng(-32768, 32767))
    self.c in vsc.rangelist(vsc.rng(-32768, 32767))
    self.d in vsc.rangelist(vsc.rng(-32768, 32767))
    self.x in vsc.rangelist(vsc.rng(-32768, 32767))
    self.y in vsc.rangelist(vsc.rng(-32768, 32767))
    self.z in vsc.rangelist(vsc.rng(-32768, 32767))
    self.w in vsc.rangelist(vsc.rng(-32768, 32767))
    self.ip_post_frame_gap in vsc.rangelist(vsc.rng(0, 1000))
    self.packet_size in vsc.rangelist(vsc.rng(64, 4096))
    self.delay_cycles in vsc.rangelist(vsc.rng(0, 100000))
    self.IsSrcCompType in vsc.rangelist(vsc.rng(0, 3))
    self.yuv_rdmaY_img_stride_1p in vsc.rangelist(vsc.rng(1, 65536))
    self.yuv_rdmaY_sbwc_lossy_comp_mode in vsc.rangelist(vsc.rng(0, 1))
    self.yuv_rdmaY_comp_64B_align in vsc.rangelist(vsc.rng(0, 1))
    self.yuv_isp_out_scale_x in vsc.rangelist(vsc.rng(0, 16384))

  @vsc.constraint
  def cr0(self):
    self.IsBypassMode in vsc.rangelist(0, 1)

  @vsc.constraint
  def cr1(self):
    self.IsYuvFormat in vsc.rangelist(0, 1, 2, 3, 4, 5)

  @vsc.constraint
  def cr13(self):
    self.stride % 16 == 0
    with vsc.if_then((self.yuv_rdmaY_comp_64B_align != 0)):
      self.stride % 64 == 0

  @vsc.constraint
  def cr31(self):
    self.IsRdmaDataFormatYuv in vsc.rangelist(4, 5, 7, 8, 16, 17, 20, 21, 32, 33)
    with vsc.if_then(self.IsRdmaDataFormatYuv.inside(vsc.rangelist(4, 5, 7, 8))):
      self.IsInBittageType == 0
    with vsc.else_if(self.IsRdmaDataFormatYuv.inside(vsc.rangelist(16, 17, 32, 33))):
      self.IsInBittageType == 1
    with vsc.else_then:
      self.IsInBittageType == 3

  @vsc.constraint
  def cr33(self):
    self.yuv_isp_image_active_width <= self.width

  @vsc.constraint
  def cr34(self):
    self.yuv_isp_crop_width <= self.yuv_isp_image_active_width

  @vsc.constraint
  def cr35(self):
    self.yuv_isp_image_crop_pre_x + self.yuv_isp_crop_width <= self.width

  @vsc.constraint
  def cr39(self):
    self.yuv_isp_image_active_height <= self.yuv_isp_org_height

  @vsc.constraint
  def cr40(self):
    self.yuv_format in vsc.rangelist(0, 1, 2)

  @vsc.constraint
  def cr41(self):
    self.yuv_packing in vsc.rangelist(0, 1, 2)

  @vsc.constraint
  def cr42(self):
    self.color_space in vsc.rangelist(0, 1, 2)

  @vsc.constraint
  def cr43(self):
    self.range_mode in vsc.rangelist(0, 1)

  @vsc.constraint
  def cr44(self):
    self.rgb_format in vsc.rangelist(0, 1, 2)

  @vsc.constraint
  def cr45(self):
    self.yuv_bit_depth in vsc.rangelist(8, 10, 12)

  @vsc.constraint
  def cr46(self):
    self.bit_depth in vsc.rangelist(8, 10, 12)

  @vsc.constraint
  def cr59(self):
    self.yuv_rdmaY_img_stride_1p % 16 == 0

  @vsc.constraint
  def cr60(self):
    self.yuv_rdmaY_sbwc_lossy_comp_mode in vsc.rangelist(0, 1)

  @vsc.constraint
  def cr61(self):
    self.yuv_rdmaY_comp_64B_align in vsc.rangelist(0, 1)

# =============================================================================
# USAGE EXAMPLE
# =============================================================================

if __name__ == '__main__':
  # Set seed for reproducibility (optional)
  # vsc.set_randstate(12345)

  # Create and randomize IspYuv2rgbRandItem
  isp_yuv2rgb_rand_item = IspYuv2rgbRandItem()
  isp_yuv2rgb_rand_item_randomized = False
  try:
    isp_yuv2rgb_rand_item.randomize()
    isp_yuv2rgb_rand_item_randomized = True
    print(f'IspYuv2rgbRandItem randomized successfully')
  except Exception as e:
    print(f'IspYuv2rgbRandItem randomize failed: {e}')

  if isp_yuv2rgb_rand_item_randomized:
    # Print field values
    print(f'  IsBypassMode = {isp_yuv2rgb_rand_item.IsBypassMode}')
    print(f'  IsYuvFormat = {isp_yuv2rgb_rand_item.IsYuvFormat}')
    print(f'  IsImageWidth = {isp_yuv2rgb_rand_item.IsImageWidth}')
    print(f'  IsImageHeight = {isp_yuv2rgb_rand_item.IsImageHeight}')
    print(f'  IsGridMode = {isp_yuv2rgb_rand_item.IsGridMode}')
